### ISSUE TITLE
Is the code covered by any license?

### ISSUE THREAD

**Issue by feedbee** [borismus/keysocket#101]
Could you include [any open source license](http://choosealicense.com/licenses/) into repository? [Without implicit defined license](http://choosealicense.com/no-license/) your code is covered by copyright low. If you do *not* want to forbid code/extension reproduction, distribution, or creation of derivative works from your code, you should include a license. Otherwise, you can do nothing, it's forbidden by copyright low by default.

**Comment by borismus** [comment]
Added apache 2.0 license.
