### ISSUE TITLE
Amazon's new player doesn't work

### ISSUE THREAD

**Issue by nemchik** [borismus/keysocket#106]
I attempted to find a fix and submit but wasn't able to figure it out. One issue for sure is the manifest has an older URL, and after updating this I can see the keys being sent to the console, but they don't seem to have any effect, and I'm not sure why.

**Comment by purdy** [comment]
Yeah, it looks like the URL format has changed:

New:
https://www.amazon.com/gp/dmusic/cloudplayer/web*

Old:
https://www.amazon.com/gp/dmusic/mp3/player*

**Comment by purdy** [comment]
Updated manifest in #118 ... haven't tested it, though. The playeraction DOM element is still there. Not sure how to debug this to help further.

**Comment by nemchik** [comment]
I think changes to the socket are also needed. I tried to complete this but was unsuccessful.

**Comment by nemchik** [comment]
Just to update this issue, #118 has not resolved this issue.

**Comment by tfaris** [comment]
I made #148 which I think fixes this. Anyone want to test for me?

**Comment by Mouseskowitz** [comment]
It's not working for me in Amazon.

**Comment by zwacky** [comment]
+1

**Comment by durango99** [comment]
I just did a quick test in developer mode with a download the extension.  I've fixed it by doing the following:

change manifest.json:

**"matches": ["https://www.amazon.com/gp/dmusic/cloudplayer/web*"],**
to
**"matches": ["https://www.amazon.com/gp/dmusic/cloudplayer/web*","https://music.amazon.com/*"],**

change keysocket-amazon-cloud-player.js to the following:

**function onKeyPress(key) {
    if (key === NEXT) {
        var nextButton = document.querySelector('span.playbackControls > span.button.nextButton.icon-fastForward');
        simulateClick(nextButton);
    } else if (key === PLAY) {
        var playPauseButton = document.querySelector('span.playbackControls > span.playButton');
        simulateClick(playPauseButton);
    } else if (key === PREV) {
        var backButton = document.querySelector('span.playbackControls > span.button.previousButton.icon-fastBackward');
        simulateClick(backButton);
    }
}**

**Comment by feedbee** [comment]
@zwacky, can you test code from latest comment and **test it**? I have no physical possibility to test Amazon Music. It it will work, I'll merge it.

**Comment by zwacky** [comment]
@tfaris's commit looks good to me, except in `extension/manifest.json` is something wrong: https://github.com/tfaris/keysocket/commit/2a903342bc4f923d0a628dbfe3a639133c0429c5#commitcomment-22072339

**Comment by feedbee** [comment]
Merged https://github.com/borismus/keysocket/pull/148 and corrected domain name in https://github.com/borismus/keysocket/pull/196. Issue will be resolved update extension update.

**Comment by feedbee** [comment]
Extension updated at store. Please, test it.

**Comment by feedbee** [comment]
Close issue untested. In case of any problems, please, reopen.
