### ISSUE TITLE
Play/Pause not working in Jamstash

### ISSUE THREAD

**Issue by EcoFreak** [borismus/keysocket#109]
Hi there, I'm using Jamstash.com with my personal subsonic server.
The extension is working for the previous and next song button and for what I can tell it's detecting the play/pause button but it's not working. 
This is a screenshot of the console after pressing the play/pause button, it's detected but an error occurs: http://puu.sh/gCKVc/ea61e95f81.png

Thanks in advance :)

**Comment by ticklemynausea** [comment]
+1 on this

**Comment by JackDunnNZ** [comment]
This is working for me using the current master branch (I fixed it [here](https://github.com/borismus/keysocket/pull/88)), but the chrome extension hasn't been updated in the store since November so the changes aren't active.

**Comment by borismus** [comment]
Just pushed a new version based on master to the store.
