### ISSUE TITLE
Prune list of music players

### ISSUE THREAD

**Issue by borismus** [borismus/keysocket#111]
This extension should support only the most popular players, and support them reliably. 

There are many players currently supported that are like #300,000 on alexa.com. For example, http://www.alexa.com/siteinfo/phishtracks.com. 

For less popular sites like these, propose a spec along the lines of http://smus.com/remote-controls-web-media/. The extension can parse the page for these salient control elements and synthesize click events on them.

**Comment by chrisdeely** [comment]
:+1: (even though I wrote the support for phishtracks :smile: )

**Comment by chrisdeely** [comment]
Actually, I'd like to propose an alternative approach here. Getting the host site to make modifications to support this extension seems unlikely until there is a well defined spec in place.

However, we could allow end users to write/install adapters for any arbitrary site they'd like. This would be similar to a developer submitting an adapter to this repo, but would not require the core extension to maintain them all.

One downside would be that we'd have to open the extension manifest to allow access to ALL URLs rather than the whitelist we use currently.

**Comment by Scarwolf** [comment]
Alternatively, what about a website providing a selectable list of music players. Depending on the music players you selected it will generate a .crx with your players. But I am not sure if that would work because of chrome forcing every .crx to come from the chrome web store.

**Comment by borismus** [comment]
Generating a crx is out of the question. I think the right approach is the
one that Valera is currently taking in
https://github.com/borismus/keysocket/pull/122

**Comment by borismus** [comment]
This does require checking every site for a meta tag, but I think it's
still worth it.

**Comment by Scarwolf** [comment]
Good luck convincing Spotify & Co. to use meta Tags like these. ATM, the don't.

**Comment by borismus** [comment]
Of course they won't. But many of the smaller players might. Some of the
players will need to be hard coded but this change would support the long
tail.

**Comment by vinyldarkscratch** [comment]
I know this is a really old issue, but honestly, I feel that pruning support for sites is an event that will push users away from Keysocket.  I feel this extension is intended to provide support where sites don't (or can't), including the biggest sites, but also the smaller ones, and to remove support for anything is something that always dissuades users from sticking with the extension.  While it's harder to maintain each and every site, we can also designate specific contributors to different websites (preferably ones they use if possible), and it shouldn't be too challenging to, if needed, update sites with simple players when someone reports an issue!

**Comment by feedbee** [comment]
I propose this policy:
1. Currently, as user can't add site for him by his own, we should merge all PR's provided the support to keep the extension single in store. If we skip RP's, users intended to push their own clones, what is not good for all.
2. A little bit later we should provide support to add player on per-user level. We need some king of plug-in system, which is common for the kind of software like Key Socket extension.
