### ISSUE TITLE
Please support Pocket Casts!

### ISSUE THREAD

**Issue by taschmidt** [borismus/keysocket#112]
https://play.pocketcasts.com/web

**Comment by Scarwolf** [comment]
Please provide me the whole source code of a static page from Pocket Casts (with the play/pause etc controls being visible to you) and I will provide the needed code as a pull request.

**Comment by taschmidt** [comment]
I hope this works.  The player must get pulled in dynamically because it wasn't in the "view source".  I had to save the rendered version from Chrome's dev tools.  It looks like it starts at line 385:

http://pastebin.com/ueEjafC6

**Comment by Scarwolf** [comment]
Alright, I created a pull requests, already tested my changes, everything is working fine (-10 Sec, Play/Pause and +30 Sec).

Pull request: https://github.com/borismus/keysocket/pull/113

If you would like to use it before the official merge from borismus, you can download the zip of https://github.com/Scarwolf/keysocket , unpack it, and then go into your chrome extension settings, enable developer-mode, and add the folder you downloaded as an unpacked extension.

**Comment by feedbee** [comment]
Merged in 2015
