### ISSUE TITLE
8tracks Support?

### ISSUE THREAD

**Issue by sashahilton00** [borismus/keysocket#124]
Hi,

I was wondering if it would be possible for you to add support for 8tracks?

Thanks.

**Comment by Scarwolf** [comment]
Give me an hour, will look into it

**Comment by sashahilton00** [comment]
any luck with this?

**Comment by dmitrybirin** [comment]
If you still needed, I've got pull request [#182](https://github.com/borismus/keysocket/pull/182) on it.

**Comment by vinyldarkscratch** [comment]
Once the issues we mentioned on the PR have been resolved by @dmitrybirin, we'll verify that it works, then merge it and release when ready.  😉

**Comment by feedbee** [comment]
Released in 0.8.1.
