### ISSUE TITLE
Youtube key functions requires update!

### ISSUE THREAD

**Issue by redd0t** [borismus/keysocket#126]
Hi there,

It was also mentioned in your Chrome extension site at review panel, and I just wanted to remind it in here aswell.

Instead of ytp-button-play it became ytp-play-button and this is true for all other buttons (prev, next..)

I've manually changed those values to test it and I can confirm it works, it just needs an update!

**Comment by maxetime** [comment]
I've already created a pull request
https://github.com/borismus/keysocket/pull/125
