### ISSUE TITLE
ON/OFF shortcut

### ISSUE THREAD

**Issue by EricHauchecorne** [borismus/keysocket#127]
I sometimes listen music on the Spotify app that handle the multimedia keys natively and sometimes on Soundcloud for which I use Key Socket.
Key Socket works great for Soundcloud, it prevent multimedia keys to reach Spotify and handle it well.

But it would be great to have the option to setup a shortcut to turn Key Socket ON/OFF like AddblockPlus does for instance, because not the only option is going in the extensions option of chrome and deactivating the extension.

Thanks for this extension!

**Comment by Scarwolf** [comment]
I am interested in this aswell, would contribute that by myself, but I am not familiar with Chrome Extension.

**Comment by mlorentz** [comment]
I have this problem too. It seems that "Key Socket" prevents other applications from using the media keys even when I'm not playing any media in Chrome.

**Comment by borismus** [comment]
This is a general problem with the way media keys are implemented in Chrome. As soon as there is any media key consumer, Chrome intercepts system media key events and does not re-broadcast them afterward. This would be a Chromium change, and I'm quite far from that code now. If someone wants to take it, though, that would be greatly appreciated.

Relevant bug is here: <https://code.google.com/p/chromium/issues/detail?id=131612>

**Comment by mlorentz** [comment]
Thanks for the explanation.
