### ISSUE TITLE
Spotify web player update not working

### ISSUE THREAD

**Issue by matallanas** [borismus/keysocket#130]
Hi, I am trying to use it with the spotify web player that has been update in the latest days. However it seems that it didn't work.
Thank you very much.

**Comment by Scarwolf** [comment]
Just tried it, works flawless for me. Just checked the keysocket-spotify.js file and the buttons are the same as the ones spotify uses. Is any other application preventing you from using media keys? Like the Spotify Application?

**Comment by matallanas** [comment]
I don't have any other application that uses the media keys open. I am using the extension for chrome but suddenly it stops working, yesterday was fine but today it didn't works with spotify but it is working with souncloud and i don't understand the problem.

**Comment by feedbee** [comment]
Extension updated at store. Please, test it.

**Comment by vinyldarkscratch** [comment]
Just fixed this so that it will support any URL that Spotify chooses to use, tested and confirmed it's fully functional.  :wink:

**Comment by feedbee** [comment]
Released on Store
