### ISSUE TITLE
Windows Server capturing keystrokes?

### ISSUE THREAD

**Issue by arielserafini** [borismus/keysocket#14]
Not sure this is the right place to post this. 

When running the Windows version of KeySocket, whenever I press  an accent key (like ~ or ' ) I get two characters instead of one (~~ instead of ~). This is messing up my ability to type in Portuguese, because the accents cannot be assigned to vowels (~a results in ã).

**Comment by borismus** [comment]
Obsolete, since Chrome supports global keys natively.
