### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by orschiro** [borismus/keysocket#140]
Dear @borismus,

Thanks a lot for this extension. I was looking for a way to control YouTube using the media keys. I couldn't find any information in the readme whether this extension is OS-specific. 

More specifically, does it support Linux?

Thankfully,

Robert

**Comment by borismus** [comment]
Yes, it depends on chrome.commands global API which should be supported.

**Comment by orschiro** [comment]
Thanks for clarifying Boris!
