### ISSUE TITLE
Publish updated version to Chrome Webstore

### ISSUE THREAD

**Issue by Whoaa512** [borismus/keysocket#146]
Currently forced to use this extension from my git clone b/c the Chrome store version doesn't have the updated Youtube CSS selectors.

**Comment by tomasbedrich** [comment]
+1

**Comment by tfaris** [comment]
+1

If there is anything that needs to be done or tested to prep for the next release I'd be happy to contribute to get the YouTube fix out there (I see a bunch of complaints in the Chrome web store!).

**Comment by Justin-Credible** [comment]
+1

**Comment by borismus** [comment]
0.7.1 pushed.
