### ISSUE TITLE
Not working on Linux (Chrome 45.0.2454.101 (64-bit))

### ISSUE THREAD

**Issue by MichaelAquilina** [borismus/keysocket#149]
None of the keys seem to be working for me and I can't figure out the best way to debug this. I'll be happy to open a pull request if I can figure out what's wrong.

**Comment by sindrenm** [comment]
:+1:

**Comment by eldamar** [comment]
I use gnome shell and had to disable the system multimedia keys, just open up keyboard settings and press backspace on play/pause, stop, next, prev to disable them. Looks like gnome shell captures the keys and not recognizing chrome as an application with multimedia support.

**Comment by feedbee** [comment]
Is it steel a problem? I use the extension on Ubuntu with Unity GUI, all works fine.

**Comment by feedbee** [comment]
Close issue. Feel free to reopen it and say a few words if you need help.
