### ISSUE TITLE
Step Forward/Step Backward

### ISSUE THREAD

**Issue by expeditor** [borismus/keysocket#150]
I would like to use `next/previous` keys as `Step Forward/Backward`. Also customizable step range would be better.

I tried few things, I couldn't simulate arrow keys on player.

**Comment by borismus** [comment]
This is probably player specific. For example if you're listening to
podcasts seeking makes more sense than skipping to the next podcast. Don't
think there are standard seek keyboard buttons.

**Comment by expeditor** [comment]
Nope. I tried on YouTube. What I want to make is about changing default behaivour of some media keys.
When I press `next media key` in my keyboard, I tried to simulate it as `left arrow key` on Youtube. By this means a few seconds back jump.

**Comment by borismus** [comment]
How would you skip tracks then? I don't want to introduce UI options for
this sort of thing.
