### ISSUE TITLE
Release Multimedia Keys When No Seekable Player Page

### ISSUE THREAD

**Issue by SerafDosSantos** [borismus/keysocket#166]
I don't know if it's feasible unless disabling the extension but could it be possible to not make the multimedia keys catchable by this extension if none of the listed websites are in use?

**Comment by feedbee** [comment]
As the extension is backed up be Chrome system-wide key bindings, it doesn't possible to enable/disable hotkeys bindings on any criteria. They are either enabled or disabled in Settings.
