### ISSUE TITLE
Google Music doesn't respond to media keys

### ISSUE THREAD

**Issue by hovissimo** [borismus/keysocket#174]
I'm using a Logitech G930 headset on Ubuntu 15.10, playing Google Music from Chrome (Version 49.0.2623.110 unknown (64-bit)).

I know my media keys on the headset are working by following the steps at https://wiki.ubuntu.com/Hotkeys/Troubleshooting

```
16:09 $ xev | sed -n 's/^.*state \([0-9].*\), keycode *\([0-9]\+\) *\(.*\), .*$/keycode \2 = \3, state = \1/p'
keycode 36 = (keysym 0xff0d, Return), state = 0x10
keycode 172 = (keysym 0x1008ff14, XF86AudioPlay), state = 0x10
keycode 173 = (keysym 0x1008ff16, XF86AudioPrev), state = 0x10
keycode 171 = (keysym 0x1008ff17, XF86AudioNext), state = 0x10
keycode 171 = (keysym 0x1008ff17, XF86AudioNext), state = 0x10
keycode 172 = (keysym 0x1008ff14, XF86AudioPlay), state = 0x10
keycode 173 = (keysym 0x1008ff16, XF86AudioPrev), state = 0x10
keycode 123 = (keysym 0x1008ff13, XF86AudioRaiseVolume), state = 0x10
keycode 122 = (keysym 0x1008ff11, XF86AudioLowerVolume), state = 0x10
^C
```

The extension is loaded (I see it in the address bar), and the shortcuts are assigned to 'Global' as per the instructions in the README

What have I missed?

Thanks

**Comment by hovissimo** [comment]
Reproduced with Chrome "Version 49.0.2623.112 m" on Windows 10

**Comment by sanscore** [comment]
OS X El Capitan, Chrome "Version 50.0.2661.102 (64-bit)"

**Comment by SoulSkin** [comment]
Have you made sure the Google Music app/extension is not conflicting? I had the same problem and figured out that Key Socket and GM app were playing then instantly pausing.

**Comment by borismus** [comment]
No longer maintained. Sorry

**Comment by feedbee** [comment]
I tested google music on Linux and MacOS today with the latest extension version. It works. I'll close this issue, but if the problem is still alive, please, reopen it.
