### ISSUE TITLE
Support for Streamsquid.com

### ISSUE THREAD

**Issue by superglenn** [borismus/keysocket#175]
This is the music service I use, It just indexes youtube clips nicely, would be nice to use keysocket with it.

**Comment by feedbee** [comment]
Would you like to make pull request for this feature?

**Comment by superglenn** [comment]
Yes, sure, thanks

**Comment by vinyldarkscratch** [comment]
Tackled in #221.  ;)

**Comment by feedbee** [comment]
Released on Store
