### ISSUE TITLE
Can't create a pull request, might be a problem on my end

### ISSUE THREAD

**Issue by showmethebitcoin** [borismus/keysocket#184]
Greetings,

I wanted to add support for Rhapsody to the extension and I have it working locally in a branch. When I tried to create a pull request, it told me I didn't have permission. My email is verified but I'm very new to github. Am I allowed to contribute?

Thanks

**Comment by showmethebitcoin** [comment]
Rhapsody was renamed to Napster today, but I'd still like to make the edit if possible.

**Comment by fieteboerner** [comment]
Hey @showmethebitcoin,

Yes you can contribute to projects.

summarized:
1. fork project
2. create branch
3. apply and commit changes
4. push to forked repo
5. create pull request

I also recommend to read the Guide: [Contributing to a Project](https://guides.github.com/activities/contributing-to-open-source/#contributing)
