### ISSUE TITLE
New VK.COM - not working

### ISSUE THREAD

**Issue by Zozu** [borismus/keysocket#185]
Please, add support of new VK.COM site. (Old is not available from today).

**Comment by borismus** [comment]
No longer maintained, sorry.

**Comment by feedbee** [comment]
Fixed in https://github.com/borismus/keysocket/pull/197, will be available after extension update.

**Comment by feedbee** [comment]
Extension updated at store. Tested.

**Comment by Zozu** [comment]
Great! It works fine. I think, the information about it should be added to description in store.

**Comment by feedbee** [comment]
I'll do it in https://github.com/borismus/keysocket/issues/203
