### ISSUE TITLE
Linux - Ubuntu 16.04 - Can't get media keys to work

### ISSUE THREAD

**Issue by iamlikeme-x** [borismus/keysocket#187]
I am unable to use the media keys for my Corsair k95 RGB keyboard, or my Logitech G502 (with a macro configured to play/pause).

I don't know whether this is just me or a general linux issue.

(My media keys on both peripherals work with dedicated music applications, just not chrome :'( )

Thanks,

**Comment by feedbee** [comment]
Is it steel actual? Do you need help?

**Comment by feedbee** [comment]
Close issue. Feel free to reopen it and say a few words if you need help.
