### ISSUE TITLE
Pandora has stopped registering

### ISSUE THREAD

**Issue by NickGeek** [borismus/keysocket#190]

**Comment by bushbaby1234** [comment]
can confirm is still an issue.

**Comment by vinyldarkscratch** [comment]
Tested as well to see if this is still broken, and I unfortunately can confirm that it is -- looks like the new layout broke the extension...

**Comment by feedbee** [comment]
Can someone of you fix the code? I can't even access Pandora because of regional filtering from their side.
@vinyldarkscratch @NickGeek

**Comment by vinyldarkscratch** [comment]
One step ahead of you, almost done in fact.  ;)

**Comment by feedbee** [comment]
Fixed in #190. I'll close the issue after extension will be updated at store.

**Comment by vinyldarkscratch** [comment]
* #207

**Comment by feedbee** [comment]
Released in 0.8.1.
