### ISSUE TITLE
Doest work with new spotify web player update

### ISSUE THREAD

**Issue by DmitryNefedov** [borismus/keysocket#193]
Hi,
has being working properly until latest (~11-12 Apr 2017) spotify update.
Currently icon isn't even active.

**Comment by zwacky** [comment]
#192

**Comment by feedbee** [comment]
Extension updated at store. Please, test it.

**Comment by vinyldarkscratch** [comment]
Just fixed this so that it will support any URL that Spotify chooses to use, tested and confirmed it's fully functional.  :wink:

**Comment by feedbee** [comment]
Released on Store
