### ISSUE TITLE
Support for listenonrepeat.com

### ISSUE THREAD

**Issue by Delfic** [borismus/keysocket#194]
The title says it all. There is no support in general for sites with embeded youtube videos. listenonrepeat is one of those sites and that I would like very much to use this feature.

**Comment by feedbee** [comment]
It's not as simple, as it seems to be. Dealing with multiple players requires the extension to know which one of them is active. By default, extension doesn't know it. So, I keep this issue open as feature request to be reviewed in future.

**Comment by ViGouRCanberra** [comment]
I'm not familiar with listenonrepeat.com, so I'm not sure if the interface changed, or I'm misunderstanding the multi-embeded video issue, but there are media controls at the top. These control the actively playing youtube embeded video. Can we just map the keys to those?

**Comment by Delfic** [comment]
I would cancel this request since I've found https://ytautoreplay.com/ which is an extension to replay videos on youtube. That being said, both in combination solve this issue.
