### ISSUE TITLE
Update extension's info in store

### ISSUE THREAD

**Issue by feedbee** [borismus/keysocket#203]
- Description (incl. supported services list)
- Icon
- Other graphics

**Comment by vinyldarkscratch** [comment]
Out of curiosity, @feedbee, may I ask what your plans are with the icon and other graphics?

**Comment by feedbee** [comment]
To make this pretty:
![image](https://cloud.githubusercontent.com/assets/1769193/25894857/32f77124-3586-11e7-8688-b018580cb711.png)

must upload this images:
![image](https://cloud.githubusercontent.com/assets/1769193/25894902/5fcdcd4c-3586-11e7-8694-d5b5af458aa8.png)

**Comment by vinyldarkscratch** [comment]
I think I get what you're saying, yeah -- one moment...

**Comment by vinyldarkscratch** [comment]
[keysocket-icon.zip](https://github.com/borismus/keysocket/files/989532/keysocket-icon.zip)
Crossing fingers that this helps in some way?

**Comment by feedbee** [comment]
SVG icon will help, thanks. Images should be a little bit different, I'll take care of them.

**Comment by vinyldarkscratch** [comment]
Of course, let me know if there's anything you need and I'll be more than happy to get it.  🙂

**Comment by feedbee** [comment]
The work is done.

![image](https://cloud.githubusercontent.com/assets/1769193/25936406/476ac9ee-3630-11e7-8df1-aa5dd9dd182d.png)
