### ISSUE TITLE
Spread the puzzle pieces and swap them out -- refactoring the code

### ISSUE THREAD

**Issue by vinyldarkscratch** [borismus/keysocket#206]
After all the pull requests have been merged, I'm thinking that it would be helpful to refactor the base extension's code.  This will be a big help with issue #166 (and #170).  Instead of script files looking like [this](https://github.com/borismus/keysocket/blob/master/extension/keysocket-builtin-player.js):

```javascript
function onKeyPress(key) {
    var videoElement = document.getElementsByTagName("video")[0];
    
    if (key === PLAY) {
        if (videoElement.paused) {
            videoElement.play();
        }
        else {
            videoElement.pause();
        }
    }
}
```

...they would look more like this:

```javascript
var videoElement = document.getElementsByTagName("video")[0];

function playpause() {
  if (videoElement.paused) videoElement.play();
  else videoElement.pause();
}

ks_bind(playpause,  null,     null, null);
     // Play/Pause, Previous, Next, Stop
```

The extension properly binds the keypresses to each function, and ignores the event if it doesn't match any of the keybinds in Chrome (so that Chrome doesn't steal the events from other apps like iTunes and Spotify when there's no music tabs open).

I'm open to suggestions, what do you guys think?

**Comment by feedbee** [comment]
Did you checked the consideration? `onKeyPress` is just a name, it's not related to any event, it just called in [shared.js](https://github.com/borismus/keysocket/blob/master/extension/shared.js#L39) in onMessage handler. Just changing function name will not help.

Nevertheless, I like two ideas of refactoring:

1. Split the handler function to parts (play, prev, next, stop)
2. Declare handler functions locally and pass them to initialization function. It's much more readable.

In [keysocket-yandex-music-and-radio.js](https://github.com/borismus/keysocket/blob/master/extension/keysocket-yandex-music-and-radio.js) I did it that way (the part about pass handlers to initialization function). But I didn't spitted handler. It could look like this:

```javascript
init(
   function () {externalAPI.togglePause();},
   function () {externalAPI.prev();}, 
   function () {externalAPI.next();}, 
   function () {externalAPI.stop();}
});

pluginLoaded('Yandex.Music');
```
js

**Comment by vinyldarkscratch** [comment]
The name changes are, of course, not all that there would be, and you did a much better job at explaining it than I did, lel.  X3  In refactoring like this, we can also implement log events to see what module is loaded, what keys are pressed, etc. across all sites without much hassle as well!

**Comment by vinyldarkscratch** [comment]
An idea formed with the whole centralized handler idea.  Many of the sites' handlers are simple scripts that obtain a specific element in the DOM and simulate a click on it.  Perhaps in the initialization function, we can pass not only a function, but also a string containing the query selector that's passed into a simple handler function?

**Comment by feedbee** [comment]
Yes, I agree with that point.

**Comment by feedbee** [comment]
Look here: https://github.com/borismus/keysocket/pull/216

**Comment by vinyldarkscratch** [comment]
If others agree with this idea, I can help with the refactoring of the site support files, adding the header comments where needed, switching everything to the new injection handler and such.  ;)  I'd say something this big would probably deserve the label of "0.9.0" as "0.8.0" is already launched ?

I also have an idea for a possible new logo if there's any desire for something like it.  I'll sketch something out and upload it right here after finishing the API spec grammar adjustments that you requested, @feedbee.  ;)

**Comment by feedbee** [comment]
I've thought a little about how the plugin API should look, and found that the best pattern here will be chained methods.

``` javascript
keySocket.init('Yandex.Music')
    .onPlayPause(function () { externalAPI.togglePause(); })
    .onStop(function () { externalAPI.stop(); })
    .onPrev(function () { externalAPI.prev(); })
    .onNext(function () { externalAPI.next(); });
```

This allows to skip handler that are not available for given service, use intellisense. Another maybe a little simpler way to write it:

``` javascript
var ks = keySocket.init('Yandex.Music');
ks.onPlayPause(function () { externalAPI.togglePause(); });
ks.onStop(function () { externalAPI.stop(); });
ks.onPrev(function () { externalAPI.prev(); });
ks.onNext(function () { externalAPI.next(); });
```

If we want to use selectors instead of event handlers, the code will be:

``` javascript
keySocket.init('Yandex.Music')
    .setPlayPauseSelector('.play')
    .setStopSelector('.stop');
```

For convenience in complex plugins it's possible to use init options to get the same effect:

``` javascript
var playPause = function () {
    externalAPI.togglePause();
};
var stopButton = ".stop";

keySocket.init('Yandex.Music', {
    "play-pause": playPause,
    "stop": stopButton
});
```

**Comment by vinyldarkscratch** [comment]
I like that, yeah!  Perhaps we can also combine the `ks.onButton()` and `ks.setButtonSelector()` functions together for convenience?

```javascript
keySocket.init('Yandex.Music')
    .onPlayPause('.play')
    .onStop('.stop')
    .onPrev(function () { externalAPI.prev(); })
    .onNext(function () { externalAPI.next(); });
```

**Comment by feedbee** [comment]
It's definitely possible, but I don't know what will be better for reading and understanding. The good point of single method is to keep smaller methods count, so contributors will have to read less.

**Comment by vinyldarkscratch** [comment]
The way I was reading it, I saw it as if either method could be chosen by the developer creating the hook, so we'd create the methods for both, and they can choose whether they want to use:

```javascript
keySocket.init('Yandex.Music')
    .onPlayPause('.play')
    .onStop('.stop')
    .onPrev(function () { externalAPI.prev(); })
    .onNext(function () { externalAPI.next(); });
```

OR, they could go for:

```javascript
var playPause = function () {
    externalAPI.togglePause();
};
var stopButton = ".stop";

keySocket.init('Yandex.Music', {
    "play-pause": playPause,
    "stop": stopButton
});
```

The first can also provide dynamic binding of the key handlers, although that's probably unintentional, in the event if may be needed?  (Example, if a site has multiple players, and focus is drawn to a different one?)

**Comment by feedbee** [comment]
Yes, the first solution provides opportunity to change handler at run-time after init. We need to support this behavior (it's pretty simple).

**Comment by feedbee** [comment]
I've finished the refactoring in #216. You can look through it. New new `plugin-api.js` have replaced old `shared.js` and all currently existed plugins have been revisited. Few plugins have been fixed, few have been deleted, all other have been refactored for new API (`plugin-api.js`) compatibility.

Now I leave a few days to test this changes in real life (hope for your help). On the next weak this code will be merged and published.

I hope, new API will make plugin development and support easier. The code now is cleaned and got ready for further movement.

**Comment by feedbee** [comment]
Merged, published.
