### ISSUE TITLE
Mediabuttons not working for other applications

### ISSUE THREAD

**Issue by thim0o** [borismus/keysocket#253]
When I have my chrome browser open with the addon enabled, but without media websites open, I cant use the mediabuttons to control spotify.

**Comment by MatheusNaldi** [comment]
Duplicate #166

**Comment by feedbee** [comment]
As the extension is backed up be Chrome system-wide key bindings, it doesn't possible to enable/disable hotkeys bindings on any criteria. They are either enabled or disabled in Settings.
