### ISSUE TITLE
Step missing from readme instructions?

### ISSUE THREAD

**Issue by thepag** [borismus/keysocket#263]
After adding the event handlers and reviewing the Chrome extension settings, which I found were already set to global, I could not get it to work. The events were not happening.

I looked at the code and noticed the meta tag required on the page to enable the function. https://github.com/borismus/keysocket/blob/master/extension/media-control-api.js#L44

After adding this to the html page, the events started happening in the page.
```
<meta name="media-controllable">
```

Please add this step to the readme for manual setup.

This was on a Mac OS X 10.13.4

Thank you for sharing.

**Comment by feedbee** [comment]
Link to documentation added to README: https://github.com/borismus/keysocket/commit/f02acff8553625c7b5729233c09c5d44df92ecdd
