### ISSUE TITLE
Twitch.tv weird behaviour

### ISSUE THREAD

**Issue by Haukef** [borismus/keysocket#273]
On Twitch.tv using the play/pause-function the first time mutes the stream, using it a second time pauses it and there is no way to get it to play again apart from clicking the play-button in the window

**Comment by mor619dx** [comment]
Same Behavior happens to me

**Comment by feedbee** [comment]
Can't reproduce. If you can, please provide a link to the video to reproduce the issue. Feel free to reopen the issue.
