### ISSUE TITLE
Add support for music.youtube.com

### ISSUE THREAD

**Issue by andrizmitnick** [borismus/keysocket#274]
it would be great to add support for music.youtube.com
thank u so much for ur work on this extension, really make my life much easier 😁

**Comment by spagettnet** [comment]
I just coded this and put in a pull request in. I honestly don't know how this type of thing works on GitHub, but if you want this to work now, you can go to my repo and clone it to your computer and then add it to chrome an unpacked extension.

**Comment by shipesmash** [comment]
Loaded the unpacked extension and no issues on YT Music or YT. Thanks @spagettnet!

**Comment by peabnuts123** [comment]
Same here. @spagettnet's PR works a dream on YouTube Music.

**Comment by feedbee** [comment]
Done, thanks. Will available @ store in 30 minutes
