### ISSUE TITLE
querySelector not working when pausing and playing.

### ISSUE THREAD

**Issue by jkgreeziak** [borismus/keysocket#276]
I've recently been trying to make an addition to the extension for the following website, a music website:
Linked [here](http://preview.codecanyon.net/item/bemusic-music-streaming-engine/full_screen_preview/13616699?_ga=2.24329338.1533294365.1528505407-21442213.1528294729).

However, when I press my keyboard's pause key, it will only pause the track, and will not play it once I press it again. If I replace the position of the selectors in the document.querySelector, it will play, but will not pause? It simply will not do both at the same time. Please see the code below.

```
function onKeyPress(key) {
     if (key === NEXT) {
         var nextButton = 
document.querySelector('.next-track.mat-icon-button');
         simulateClick(nextButton);
     } else if (key === PLAY) {
         var playPauseButton = 
document.querySelector('.play-track.mat-icon-button, 
.pause-track.mat-icon-button');
                simulateClick(playPauseButton);
     } else if (key === PREV) {
         var backButton = 
document.querySelector('.previous-track.mat-icon-button');
         simulateClick(backButton);
     } else if (key === STOP) {
         var stopButton = 
frame.contentDocument.querySelector('.pause-track.mat-icon-button');
         simulateClick(stopButton);
     }
}
```

**Comment by feedbee** [comment]
Your query always gives you the same button -- play. What you need is to change it to always select unhidden  button only:
```
...
} else if (key === PLAY) {
    var playPauseButton = 
    document.querySelector('.play-track.mat-icon-button:not(.hidden), .pause-track.mat-icon-button:not(.hidden)');
    simulateClick(playPauseButton);
} 
...
```
