### ISSUE TITLE
Add .github folder

### ISSUE THREAD

**Issue by coliff** [borismus/keysocket#283]
To help contributors and folks requesting support etc it'd be good to add the following:
```
\.github\CONTRIBUTING.md
\.github\ISSUE_TEMPLATE.md
\.github\PULL_REQUEST_TEMPLATE.md
\.github\SUPPORT.md
```

**Comment by feedbee** [comment]
@coliff, please feel free to create and fill in the files if you're interested. In other case it's better to close the issue.
