### ISSUE TITLE
YouTube Gaming Support

### ISSUE THREAD

**Issue by coliff** [borismus/keysocket#284]
It'd be nice to add support for https://gaming.youtube.com/

**Comment by feedbee** [comment]
Feel free to create a Pull Request on this.

**Comment by GerardSmit** [comment]
Note: YouTube Gaming is stopping their services because it's being merged into YouTube. More information: https://support.google.com/youtubegaming/answer/9135119.

**Comment by coliff** [comment]
Thanks for the headsup on that @GerardSmit - I'll close this issue then. 👍
