### ISSUE TITLE
Doesn't work on macOS Mojave

### ISSUE THREAD

**Issue by ecnepsnai** [borismus/keysocket#293]
I've noticed that since updating to macOS Mojave I can no longer use the media keys to control Google Play music, as when I do it opens iTunes (super annoying).

OS: 10.14 (18A391)  
Chrome: 69.0.3497.100 (Official Build) (64-bit)
Site: play.google.com

**Comment by tkornai** [comment]
For me this solved it: https://www.reddit.com/r/chrome/comments/9j7f9r/media_keys_google_play_music_are_not_working_on/

**Comment by ecnepsnai** [comment]
@tkornai That did the trick, thanks!

Closing as this isn't a problem with the extension, but with how macOS Mojave considers the media keys a "accessibility" feature.
