### ISSUE TITLE
Mojave; Chrome 69, Yandex.music

### ISSUE THREAD

**Issue by eudaco** [borismus/keysocket#294]
Touch bar media keys not works in Mojave - Chrome 69.0.3497 - Yandex.music

**Comment by pavel-slepenkov** [comment]
@axejko not sure if it's the same case but make sure that Chrome has all required permission to control your computer via `System Preferences` -> `Security & Privacy` -> `Accessibility`. It fixed same issue with physical media keys on MBP'15

**Comment by brunogdesign** [comment]
Worked for me too! Thanks @pavel-slepenkov 👍
