### ISSUE TITLE
Missing from Chrome Web Store

### ISSUE THREAD

**Issue by Delfic** [borismus/keysocket#297]
Hello, I have this extension and wanted to share with a colleague.
Alas, it's no longer in the Chrome Web Store
When I click "See in Chrome Web Store" I get a `404` here: `https://chrome.google.com/webstore/detail/fphfgdknbpakeedbaenojjdcdoajihik`

Will it be available again somehow?

**Comment by valery-leontyev-idt** [comment]
Looking into it. Have no idea why it was removed

**Comment by feedbee** [comment]
I still can't find out what made Google remove it.

> Dear Developer, Your Google Chrome item, "Key Socket Media Keys," with ID: fphfgdknbpakeedbaenojjdcdoajihik did not comply with our policies and was removed from the Google Chrome Web Store. Your item did not comply with the following section of our policy:
>Do not post repetitive content. 
>Do not attempt to change the placement of any Product in the store, or manipulate any Product ratings or reviews, by unauthorized means, such as fraudulent installs, paid or fake reviews or ratings, or offering incentives to rate Products. 
>Do not post an app if the primary functionality is to link to a website not owned by the developer posting the app. 
>Do not post an app where the primary functionality is to install or launch another app, theme, or extension. For example, you cannot post an app if its primary function is to launch a desktop app that the user has already installed. Another example of a disallowed practice would be to post a packaged app that just launches a website. 
>Your app must comply with Google's Webmaster Quality Guidelines
>If you'd like to re-submit your item, please make the appropriate changes to the item so that it complies with our policies, then re-publish it in your developer dashboard. Please reply to this email for issues regarding this item removal.

I tried to leave minimum amount of text in desc, but it didn't help.

**Comment by bigcooki3** [comment]
I'm seeing the extension back up again 😃
