### ISSUE TITLE
Can't Play/Pause in other apps when the extension is active

### ISSUE THREAD

**Issue by Tom60chat** [borismus/keysocket#315]
When I press my media key button it don't pause my music apps because the extension have a priority and is anoying.

**Comment by feedbee** [comment]
Hi @Tom60chat. Sorry to say that but key bindings is managed by OS and it's impossible to bind keys to more than one app in the same time. Priority gets the application which has registered bindings later. There is no any bindings management into the extension - all is done by Chrome. So, what you're asking is impossible to resolve.
