### ISSUE TITLE
Skip/FastForward key doesn't seem to work

### ISSUE THREAD

**Issue by TLuigi003** [borismus/keysocket#319]
Tech Info
Chrome 73.0.3683.86 on Windows 10(not fully updated)
Trying on Youtube Music
Console log doesn't seem to register anything at key press.

What should it do?
Skip to the next song

What does it do?
Nothing.

I may fix it if a find some time, but since IDK when is that i just register the issue here

**Comment by GerardSmit** [comment]
Fixed in https://github.com/borismus/keysocket/pull/320 with an explanation why it doesn't work anymore.

**Comment by TLuigi003** [comment]
Oh, thanks for linking
Not sure if I should close this right away or wait until merge.
Nice job!

**Comment by GerardSmit** [comment]
No probs! I've added `fixes #319` in the PR so it will close automatically when it is merged.
