### ISSUE TITLE
Update Deezer support

### ISSUE THREAD

**Issue by Dzieni** [borismus/keysocket#32]
Every button does the task twice. Also, the "previous" button goes to the next song.

**Comment by feedbee** [comment]
Currently: play/pause works normal, prev and next are not wirking

**Comment by feedbee** [comment]
Tested it again and see that all works fine. If you have any troubles now, please write a comment. If not, I'll close this issue.

**Comment by feedbee** [comment]
Close issue. Feel free to reopen it and say a few words if you need help.
