### ISSUE TITLE
Next not working for Youtube Music

### ISSUE THREAD

**Issue by ribas1a3** [borismus/keysocket#323]
Play/Pause and previous work. But the next is not working for Youtube music, works on spotify though.

**Comment by johnmhm** [comment]
I have this issue on Brave Version 0.62.51 Chromium: 73.0.3683.103 (Official Build) (64-bit)

**Comment by antonlookinpoynt** [comment]
Same 
Chrome Version 73.0.3683.103 (Official Build) (64-bit)
OS X Version 10.14.4 (18E226)

**Comment by look1n** [comment]
Same 
Chrome Version 73.0.3683.103 (Official Build) (64-bit)
OS X Version 10.14.4 (18E226)
