### ISSUE TITLE
Not working for Spotify

### ISSUE THREAD

**Issue by stewx** [borismus/keysocket#354]
I am not able to use the extension with Spotify, to pause, play, etc.

**Comment by stewx** [comment]
Looks like the CSS classes are no longer in use:

![image](https://user-images.githubusercontent.com/6986171/101918578-e3a4cf80-3b9f-11eb-9124-4115410309a5.png)

**Comment by vyang17** [comment]
Take a look at this PR:
https://github.com/borismus/keysocket/pull/355/files

Copy pasta the update to your local files and then load in the extension from local source. Then it should work again.

**Comment by stewx** [comment]
I just discovered that I don't need this extension anymore since Chrome natively gives control over Spotify, etc with media keys. The PR looks good though
