### ISSUE TITLE
Broken for players served over HTTPS  (e.g. Google Music)

### ISSUE THREAD

**Issue by max99x** [borismus/keysocket#59]
On Chrome 36 (Linux, but probably doesn't matter), KeySocket is broken by new security limitations:

[blocked] The page at 'https://play.google.com/music/listen?u=1#/all' was loaded over HTTPS, but ran insecure content from 'ws://localhost:1337/': this content should also be loaded over HTTPS.

It's possible that just changing the scheme to "wss" will solve this, but I don't know if all of the server implementations which KeySocket uses automatically support secure connections.

**Comment by borismus** [comment]
HTTPs doesn't have anything to do with this. Closing
