### ISSUE TITLE
Permissions too broad when installing

### ISSUE THREAD

**Issue by brysgo** [borismus/keysocket#69]
I read through the manifest and it seems like the permissions are specific enough that I would use this extension. However, when I install from the chrome webstore I get a permission prompt that looks like this:

![screen shot 2014-08-14 at 10 47 43 am](https://cloud.githubusercontent.com/assets/57716/3921525/416ead68-23c2-11e4-9119-f0ad3b1c2ff9.png)

**Comment by borismus** [comment]
Got rid of the <all_urls> permission, should be resolved.
