### ISSUE TITLE
Media Keys don't function outside of browser

### ISSUE THREAD

**Issue by corehop** [borismus/keysocket#78]
To recreate:
Have Chrome open with extension enabled, not using any streaming service.
Open Spotify desktop client.
Notice that the Media Keys do not function.
Disable KeySocket Extension in Chrome - Media Keys work again in Spotify.

Perhaps KeySocket can unhook the keypress events when there is no site open to receive the keypresses?

**Comment by borismus** [comment]
If this is a Chrome keys bug, please log a new issue on <http://crbug.com/new>
