### ISSUE TITLE
Only works sometimes on Tidal Hifi

### ISSUE THREAD

**Issue by Wheatability** [borismus/keysocket#86]
On Tidal, the plugin seems to work occasionally but does not work for the majority of the time. No response from any hotkeys. It does work fine on youtube, google music, and anything else i tried..

**Comment by mcoalson** [comment]
Can confirm... same thing happening here.

**Comment by brandondurham** [comment]
Same here.

**Comment by tg90nor** [comment]
I tested running the javascript from keysocket-tidal.js manually in a chrome console, and it worked fine. But for some reason it does not work for me when using the extension.

**Comment by torbjornvatn** [comment]
It stopped working for me today for no obvious reason

**Comment by feedbee** [comment]
My test showed all works perfect on https://listen.tidal.com/. If you have any problems, please write comment. If not, I'll close this issue in few days.
